packageExtensions:
  "@chakra-ui/gatsby-plugin@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/transition@*":
    dependencies:
      "framer-motion": "*"
  "@chakra-ui/checkbox@*":
    dependencies:
      "framer-motion": "*"
  "@chakra-ui/icon@*":
    dependencies:
      "@chakra-ui/system": "*"
  gatsby-plugin-image@*:
    dependencies:
      "@emotion/react": "*"
  gatsby-source-graphql@*:
    dependencies:
      "@apollo/client": "*"
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: false

pnpIgnorePatterns:
  - ./packages/cms

yarnPath: .yarn/releases/yarn-3.1.0.cjs
