packageExtensions:
  gatsby-source-graphql@*:
    dependencies:
      "@apollo/client": "*"
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpIgnorePatterns:
  - ./packages/cms

yarnPath: .yarn/releases/yarn-3.0.2.cjs
