name: Deploy Sanity Studio
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
              node-version: 16.x
        - name: Install dependencies
          run: |
              cd rttp-jam-cms && yarn
        - name: Deploy Sanity
          run: |
              set -e
              cat << EOF > .env.production
              EOF
              SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn sanity deploy
