name: Deploy Sanity Studio

on:
  push:
    branches: [master]
    paths:
      - "packages/cms/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn workspace cms install

      - name: Deploy Sanity
        run: |
          set -e
          cat << EOF > .env.production
          EOF
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn workspace cms deploy
